database:
  # mysql:
  #   user: root
  #   password: zhangxinghui
  #   address: 192.168.80.128
  #   port: 3306
  #   schema: 3X

  mysql:
    user: root
    password: 123456
    address: 10.2.98.225
    port: 3306
    schema: 3X